return {
    -- ["Slime"] = {main = "WAR", sub = "WAR"}, --What is "Astoltian" and is this a duplicate?
    ["Clot"] = {main = "RDM", sub = "WAR"},
    ["Gold Slime"] = {main = "THF", sub = "WAR"},
    ["Boil"] = {main = "PLD", sub = "DRK"},
    ["Hecteyes"] = {main = "BLM", sub = "WAR"},
    ["Flan"] = {main = "BLM", sub = "WAR"},
    ["Gold Flan"] = {main = "WAR", sub = "WAR"},
    ["Alabaster flan"] = {main = "WHM", sub = "PLD"},
    ["Leech"] = {main = "WAR", sub = "WAR"},
    ["Azure Leech"] = {main = "WAR", sub = "WAR"},
    ["Obdella"] = {main = "DRK", sub = "WAR"},
    ["Slug"] = {main = "WAR", sub = "WAR"},
    ["Sandworm"] = {main = "WAR", sub = "WAR"},
    ["Pygmy Sandworm"] = {main = "WAR", sub = "WAR"},
    ["Gigaworm"] = {main = "WAR", sub = "BLM"},
    ["Crab"] = {main = "PLD", sub = "PLD"},
    ["Basket-burdened (Hermitage) Crab"] = {main = "BLM", sub = "PLD"},
    ["Vermilion Crab"] = {main = "PLD", sub = "RDM"},
    ["Basket-burdened (Hermitage) Vermilion Crab"] = {main = "RDM", sub = "PLD"},
    ["Porter Crab"] = {main = "DRK", sub = "PLD"},
    ["Toad"] = {main = "WAR", sub = "WAR"},
    ["Azure Toad"] = {main = "BRD", sub = "BLM"},
    ["Vermilion Toad"] = {main = "RDM", sub = "BRD"},
    ["Pugil"] = {main = "SAM", sub = "BLM"},
    ["Jagil"] = {main = "COR", sub = "COR"},
    ["Sea Monk"] = {main = "WAR", sub = "WAR"},
    ["Azure Sea Monk"] = {main = "SAM", sub = "WHM"},
    ["Orobon"] = {main = "WAR", sub = "WAR"},
    ["Pygmy Orobon"] = {main = "WAR", sub = "WAR"},
    ["Ogrebon"] = {main = "DRK", sub = "WAR"},
    ["Uragnite"] = {main = "PLD", sub = "PLD"},
    ["Limascabra"] = {main = "PLD", sub = "BLM"},
    ["Ruszor"] = {main = "DRK", sub = "BLM"},
    ["Buffalo"] = {main = "PLD", sub = "PLD"},
    ["Rabbit"] = {main = "WAR", sub = "WAR"},
    ["Onyx Rabbit"] = {main = "WAR", sub = "BLM"},
    ["Alabaster Rabbit"] = {main = "WAR", sub = "WHM"},
    ["Lapinion"] = {main = "WHM", sub = "BLM"},
    ["Dhalmel"] = {main = "WAR", sub = "WAR"},
    ["Tiger"] = {main = "WAR", sub = "WAR"},
    ["Smilodon"] = {main = "WAR", sub = "WAR"},
    ["Legendary Tiger"] = {main = "WHM", sub = "THF"},
    ["Coeurl"] = {main = "WAR", sub = "WAR"},
    ["Lynx"] = {main = "WAR", sub = "BLM"},
    ["Collared Lynx"] = {main = "RDM", sub = "BLM"},
    ["Opo-opo"] = {main = "WAR", sub = "WAR"},
    ["Gnole"] = {main = "MNK", sub = "MNK"},
    ["Behemoth"] = {main = "WAR", sub = "THF"},
    ["Elasmoth"] = {main = "DRK", sub = "THF"},
    ["Manticore"] = {main = "WAR", sub = "WAR"},
    ["Legendary Manticore"] = {main = "RDM", sub = "BLM"},
    ["Sheep"] = {main = "WAR", sub = "WAR"},
    ["Karakul"] = {main = "WAR", sub = "WAR"},
    ["Ram"] = {main = "WAR", sub = "WAR"},
    ["Marid"] = {main = "WAR", sub = "WAR"},
    ["Orthrus"] = {main = "WAR", sub = "BLM"},
    ["Bat"] = {main = "WAR", sub = "WAR"},
    ["Bat Trio"] = {main = "WAR", sub = "WAR"},
    ["Vermilion Bat"] = {main = "RDM", sub = "WAR"},
    ["Vermilion Bat Trio"] = {main = "RDM", sub = "WAR"},
    ["Bird"] = {main = "WAR", sub = "WAR"},
    ["Onyx Bird"] = {main = "THF", sub = "BLM"},
    ["Colibri"] = {main = "RDM", sub = "RDM"},
    ["Tukalibri"] = {main = "BRD", sub = "THF"},
    ["Apkallu"] = {main = "MNK", sub = "MNK"},
    ["Inguza"] = {main = "NIN", sub = "MNK"},
    ["Cockatrice"] = {main = "WAR", sub = "WAR"},
    ["Ziz"] = {main = "BLM", sub = "WAR"},
    ["Roc"] = {main = "WHM", sub = "BRD"},
    ["Legendary Roc"] = {main = "WAR", sub = "RDM"},
    ["Gagana"] = {main = "BLM", sub = "BRD"},
    ["Hippogryph"] = {main = "THF", sub = "BLM"},
    ["Amphitere"] = {main = "WAR", sub = "BLM"},
    ["Sanguiptere"] = {main = "BLM", sub = "WAR"},
    ["Name"] = {main = "Main", sub = "Sub"},
    ["Bugard"] = {main = "WAR", sub = "WAR"},
    ["Abyssobugard"] = {main = "WAR", sub = "BLM"},
    ["Lizard"] = {main = "WAR", sub = "WAR"},
    ["Hill Lizard"] = {main = "Lizard", sub =""},
    ["Ashen Lizard"] = {main = "WAR", sub = "BLM"},
    ["Wivre"] = {main = "WAR", sub = "WAR"},
    ["Unusual Wivre"] = {main = "WAR", sub = "BLM"},
    ["Adamantoise"] = {main = "PLD", sub = "PLD"},
    ["Pygmy Adamantoise"] = {main = "PLD", sub = "PLD"},
    ["Legendary Adamantoise"] = {main = "PLD", sub = "RDM"},
    ["Ferromantoise"] = {main = "PLD", sub = "BLM"},
    ["Raptor"] = {main = "WAR", sub = "WAR"},
    ["Emerald Raptor"] = {main = "WAR", sub = "WAR"},
    ["Ruby Raptor"] = {main = "WAR", sub = "WAR"},
    ["Eft"] = {main = "WAR", sub = "WAR"},
    ["Tarichuk"] = {main = "WAR", sub = "BLM"},
    ["Peiste"] = {main = "WAR", sub = "WAR"},
    ["Sibilus"] = {main = "WAR", sub = "BLM"},
    ["Mandragora"] = {main = "MNK", sub = "MNK"},
    ["Korrigan"] = {main = "MNK", sub = "BLM"},
    ["Lycopodium"] = {main = "MNK", sub = "WHM"},
    ["Mandragora (Pygmy)"] = {main = "MNK", sub = "MNK"},
    ["Pachypodium"] = {main = "MNK", sub = "MNK"},
    ["Adenium"] = {main = "RDM", sub = "MNK"},
    ["New Year's Mandragora"] = {main = "MNK", sub = "NIN"},
    ["Sabotender"] = {main = "WAR", sub = "WAR"},
    ["Sabotender Florido"] = {main = "WAR", sub = "RDM"},
    ["Flytrap"] = {main = "WAR", sub = "WAR"},
    ["Sapling"] = {main = "WAR", sub = "WAR"},
    ["Treant"] = {main = "WAR", sub = "BLM"},
    ["Funguar"] = {main = "WAR", sub = "WAR"},
    ["Coppercap"] = {main = "WAR", sub = "WAR"},
    ["Morbol"] = {main = "WAR", sub = "WAR"},
    ["Morbol (Pygmy)"] = {main = "WAR", sub = "WAR"},
    ["Scarce Morbol"] = {main = "WAR", sub = "WAR"},
    ["Ameretat"] = {main = "WAR", sub = "WAR"},
    ["Purbol"] = {main = "WAR", sub = "BLM"},
    ["Rafflesia"] = {main = "DRK", sub = "WAR"},
    ["Mitrastema"] = {main = "DRK", sub = "BLM"},
    ["Goobbue"] = {main = "WAR", sub = "WAR"},
    ["Panopt"] = {main = "BLM", sub = "BLM"},
    ["Antlion"] = {main = "WAR", sub = "WAR"},
    ["Onyx Antlion"] = {main = "WAR", sub = "BLM"},
    ["Formiceros"] = {main = "DRK", sub = "BLM"},
    ["Bee"] = {main = "WAR", sub = "WAR"},
    ["Vermilion and Onyx Bee"] = {main = "WAR", sub = "RDM"},
    ["Zaffre Bee"] = {main = "WAR", sub = "BLM"},
    ["Beetle"] = {main = "PLD", sub = "PLD"},
    ["Onyx Beetle"] = {main = "PLD", sub = "BLM"},
    ["Gamboge Beetle"] = {main = "PLD", sub = "RDM"},
    ["Fly"] = {main = "WAR", sub = "WAR"},
    ["Vermilion and Onyx Fly"] = {main = "RDM", sub = "WAR"},
    ["Wamouracampa"] = {main = "PLD", sub = "PLD"},
    ["Wamoura"] = {main = "WAR", sub = "PLD"},
    ["Vermillion Wamoura"] = {main = "BLM", sub = "PLD"},
    ["Ladybug"] = {main = "THF", sub = "THF"},
    ["Gold Ladybug"] = {main = "RDM", sub = "THF"},
    ["Crawler"] = {main = "WAR", sub = "WAR"},
    ["Eruca"] = {main = "WAR", sub = "RDM"},
    ["Emerald Crawler"] = {main = "WHM", sub = "BLM"},
    ["Pygmy Emerald Crawler"] = {main = "WHM", sub = "BLM"},
    ["Scorpion"] = {main = "WAR", sub = "WAR"},
    ["Scolopendrid"] = {main = "WAR", sub = "BLM"},
    ["Unusual Scolopendrid"] = {main = "DRK", sub = "BLM"},
    ["Chigoe"] = {main = "THF", sub = "THF"},
    ["Azure Chigoe"] = {main = "THF", sub = "BLM"},
    ["Spider"] = {main = "WAR", sub = "WAR"},
    ["Reticulated Spider"] = {main = "WAR", sub = "DRK"},
    ["Vermilion and Onyx Spider"] = {main = "WAR", sub = "RDM"},
    ["Diremite"] = {main = "DRK", sub = "DRK"},
    ["Arundimite"] = {main = "DRK", sub = "DRK"},
    ["Gnat"] = {main = "WAR", sub = "THF"},
    ["Midge"] = {main = "BLM", sub = "THF"},
    ["Slime"] = {main = "WAR", sub = "WAR"},
    ["She-Slime"] = {main = "WAR", sub = "WAR"},
    ["Metal Slime"] = {main = "BLM", sub = "WAR"},
    ["Spriggan"] = {main = "WAR", sub = "BLM"},
    ["Spriggan.C"] = {main = "WAR", sub = "BLM"},
    ["Spriggan.G"] = {main = "BLM", sub = "WAR"},
}
--[[luacheck: ignore (0vt	hS"gvS]/	s= {main = wysiw"Ea, sub =llxysiw"Ea},ld$)]]

